dist: bionic
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ppa:ubuntu-toolchain-r/test
    packages:
      - gcc-9
      - g++-9
      - libsdl2-dev,
      - libglm-dev
      - libopenal-dev
      - libbullet-dev

cache:
  directories:
    - .cache
    - $HOME/.ccache
  apt: true

before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
