dist: bionic
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-9 libsdl2-dev libglm-dev libopenal-dev libbullet-dev -y

cache:
  directories:
    - .cache
    - $HOME/.ccache
  apt: true

before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
