dist: bionic
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-9 g++-9 libsdl2-dev libglm-dev libopenal-dev libbullet-dev -y

before_script:
  - export CC=gcc-9
  - export CXX=g++-9
  - mkdir -p build && cd build
  - cmake ..

script:
  -cmake --build .
